# Use root/example as user/password credentials
version: '3.1'

services:
  mariadb:
    image: mariadb
    volumes: 
      - /usr/local/cjl/data2:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root*!"
      MYSQL_USER: "keycloak"
      MYSQL_PASSWORD: "Password1"
      MYSQL_DATABASE: "keycloak"

  keycloak:
    image: cjl-keycloak:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
            #DB_VENDOR: mariadb
            #DB_HOST: localhost
            #DB_PORT: 3306
            #DB_DATABASE: cjl
            #PROXY_ADDRESS_FORWARDING: "true"
      DB_PASSWORD: "Password1"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin123"
      JAVA_OPTS: "-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
      #volumes:
      #- /etc/letsencrypt/live/auth.my-cjl.fr/fullchain.pem:/etc/x509/https/tls.crt
      #- /etc/letsencrypt/live/auth.my-cjl.fr/privkey.pem:/etc/x509/https/tls.key
    depends_on:
      - mariadb

        #  nginx:
        #image: nginx:latest
        #volumes:
        # - /usr/local/cjl/nginx/nginx.conf:/etc/nginx/nginx.conf
        #ports:
        #- "80:80"
        #- "443:443"i
